### ISSUE TITLE
关于C端的一些问题

### ISSUE THREAD

**Issue by hellohello-tom** [daxnet/we-text#1]
您好，在阅读了您的wetext项目，有如下几个问题：
1、C端在处理时返回状态，您是怎么处理的，例如银行转账，账户余额不足此类提示
2、web项目必须基于wetext.service这个控制台？能否挂载到服务上。
3、假设，对于用户聚合根来讲，假设我有一个修改密码的业务，我判断密码发生改变，这个动作作为事件被派发下去，但是我却提交了整个聚合根，对于数据库来讲就修改了所有字段，这样是否合理呢？

**Comment by daxnet** [comment]
您好！
1. 目前wetext项目由于急于rabbitmq，所以都是异步消息通信，这是一个弊端，也就是说，命令发出后并没有直接得到反馈，也无法得到反馈。这是CQRS的特点，当然也有人会人为地让CommandHandler去等待Command处理结果，不过这样做并不纯正（好比烧红烧肉，虽然可以做到，但是味道不地道）。还有一种办法就是，在Client使用JS对Query端进行轮询，如果得到了结果，那么就刷新页面。我的做法你可以看到其实有点类似第二种，不过是让用户通过点击回退按钮，回到主页，在等待用户点击的这一小段时间，服务器已经完成了消息的处理并在Query端产生了结果，当回退到主页时，主页又会发出查询请求，于是，处理结果就被更新到页面上了。这其实是打了个擦边球。如果用户操作很快，而服务器又没完成处理，那么用户即使回退到主页，也看不到最新结果，需要等一段时间再刷新才能看到
2. 当然可以，事实上这个控制台就是一个web api的宿主程序，你将web api部署到IIS等服务上，完全没有问题
3. 仓储的概念不会去考虑数据库会如何操作，也就是它不会管数据库的死活。仓储关心的是聚合对象本身。当然，在实际应用中，仓储的实现技术是多样化的，比如使用类似NH或者EF的ORM来实现，这些ORM框架本身会跟踪对象各字段的变化情况，甚至会非常智能地产生优化过的SQL语句，不管怎样，你的问题完全可以由ORM兜住，至于仓储，只需要负责貌美如花就行了
